### ISSUE TITLE
Table of contents link does not work when headers contain special characters

### ISSUE THREAD

**Issue by Hmnt39** [TheRenegadeCoder/SnakeMD#163]
Headers in markdown have an anchor which is used for links, format is '#' then the header text converted to lower-case, spaces replaced with hyphens, and special characters removed.

The Table of Contents in snakemd has a link to the header by converting to lower-case and replacing spaces with hyphens, but does not remove special characters. This means that some of the links in the table of content will not work.

For example I have a header level 2, with text "Yaml's list", when I create a ToC the link to this is #yaml's-list, but should be #yamls-list, i.e. without the apostrophe symbol. Clicking on the link does not take me to the header section of the document as it should do..

**Comment by jrg94** [comment]
Phenomenal catch! I don't know how soon I will get to this, but I can add some testing to catch this and start looking for a fix.
