### ISSUE TITLE
Allow multiple heading levels in table of contents

### ISSUE THREAD

**Issue by ddukki** [TheRenegadeCoder/SnakeMD#41]
Only showing the level 2 headings is a bit restrictive. Maybe allow for two-element list or a tuple defining the top and bottom level of the range of headings that the user would like to show in the TOC. The Table of Contents would then be a nested-list of headings. Default would remain just the level 2 headings, with the list/tuple being a range of a single value [2, 2].

**Comment by jrg94** [comment]
Ahh, great idea! Seems like a pretty easy change given the source code. I'll try to have something out for this over the next couple days.

**Comment by jrg94** [comment]
Here's the line of code for reference: https://github.com/TheRenegadeCoder/SnakeMD/blob/583fac71d171f5593aba586bf59f2660fcba01e9/snakemd/generator.py#L753

**Comment by jrg94** [comment]
Alright, that feature should be added in 0.8.0. Let me know if you run into any issues with it.

**Comment by ddukki** [comment]
@jrg94 Appreciate you taking the time to make the enhancement! Unfortunately, it doesn't adhere to the strict markdown linting rules, so it throws a warning [MD005](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md005) and doesn't render properly. It's expecting the sublevel heading to start directly underneath the parent heading's first character. For example:

```md
1. [heading 1](#heading-1)
2. [heading 2](#heading-2)
   1. [subheading 1](#subheading-1) // this would pass
  2. [subheading 2](#subheading-2) // this would fail
```

One nice thing about markdown is that if you just set all the numbers to 1, markdown will automagically set the proper numbers.

```md
1. [heading 1](#heading-1)
1. [heading 2](#heading-2)
   1. [subheading 1](#subheading-1) // this would pass
   1. [subheading 2](#subheading-2) // this would fail
```
will still render as

1. [heading 1](#heading-1)
2. [heading 2](#heading-2)
   1. [subheading 1](#subheading-1)
   2. [subheading 2](#subheading-2)
   
so you don't have to worry about counting characters. Hopefully, this is a simple edit, but if not, I would be more than willing to contribute.

**Comment by jrg94** [comment]
Ahhh I see! That makes a lot of sense. I think shifting to just showing `1.` means I can use 3 spaces as the standard. Is that what you're saying?

**Comment by ddukki** [comment]
Yes! That's the basic idea. I think there'll be some cases where someone might use unordered lists somewhere in nested lists, so you may have to check whether to indent 2 or 3 spaces, but yeah. At least for Table of Contents, it should be alright to assume that the indent will always be 3 spaces, since that's the way you've coded it.

**Comment by jrg94** [comment]
I'm experimenting with the linter you linked ([this playground](https://dlaa.me/markdownlint/)), and I'm noticing that four spaces seems to work fine. Is that another option?

```
# Indentation Test

1. [Section 1](#section-1)
    1. [Subsection 1](#subsection-1)
    2. [Subsection 2](#subsection-2)
2. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
3. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
4. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
5. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
6. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
7. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
8. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
9. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)
10. [Section 2](#section-2)
    1. [Subsection 3](#subsection-3)

```

Also, I'm trying to read through the [CommonMark](https://spec.commonmark.org/0.30/) spec at the same time to get a feel for these rules. I'd like to document whatever standard we're trying to follow with this tool.

**Comment by jrg94** [comment]
Actually, I can solve it as you laid it out pretty easily. I'm in the process of fixing it now.

**Comment by ddukki** [comment]
Absolutely! I didn't mean to make you enforce a full ruleset! Apologies if I've added undue things onto your plate! Thanks so much for your efforts.

**Comment by jrg94** [comment]
Haha no it's all good! If more folks are going to use this, the least we can do is get it right.

**Comment by jrg94** [comment]
Alright, it should be good to go. I added significantly more testing this time around to be sure lists render properly.
