### ISSUE TITLE
UnicodeEncodeError when using .output_page

### ISSUE THREAD

**Issue by ichsanulamal** [TheRenegadeCoder/SnakeMD#54]
I am using `.output_page` and I get the following error:
"""
C:\ProgramData\Anaconda3\lib\encodings\cp1252.py in encode(self, input, final)
     17 class IncrementalEncoder(codecs.IncrementalEncoder):
     18     def encode(self, input, final=False):
---> 19         return codecs.charmap_encode(input,self.errors,encoding_table)[0]
     20 
     21 class IncrementalDecoder(codecs.IncrementalDecoder):

UnicodeEncodeError: 'charmap' codec can't encode characters in position 678150-678153: character maps to <undefined>
"""

**Comment by jrg94** [comment]
Thanks for the catch! I’ll probably have to add a codec feature to output_page. In the meantime, you can try calling ‘str’ on the document object. Then maybe you can try writing that string to a file by hand.
