### ISSUE TITLE
Add tables row-by-row

### ISSUE THREAD

**Issue by hughbe** [TheRenegadeCoder/SnakeMD#64]
I need to write hundreds of rows to markdown, and want to write the header, then run an async function to get some output and then send write rows to markdown.

Currently, I need to create an array to include all the rows, then write everything to the list.

It would be good to have a way to write a table, e.g.:

```py
doc.write_table_header(...)
for row in long_running_iterator():
    doc.write_table_row(...)
```

**Comment by jrg94** [comment]
Oh, I really like this idea! I think the way this would work best with the repo is with the Table object directly. I'd be open to having something like this:

```python
table = Table(header)
for row in long_running_iterator():
    table.add_table_row(...)
doc.add_element(table)
```
