### ISSUE TITLE
Line breaks inside paragraph

### ISSUE THREAD

**Issue by damascene** [TheRenegadeCoder/SnakeMD#68]
I would like to be able to have line breaks inside paragraph to use with [Pelican](https://github.com/getpelican/pelican). [example metadata](
https://docs.getpelican.com/en/3.6.3/content.html#file-metadata) in Pelican Mardown file:

```
Title: My super title
Date: 2010-12-03 10:20
Modified: 2010-12-05 19:30
Category: Python
Tags: pelican, publishing
Slug: my-super-post
Authors: Alexis Metaireau, Conan Doyle
Summary: Short version for index and feeds

This is the content of my super blog post.
```
Currently such string is grouped in one line in SnakeMD

```
Title: My super title Date: 2010-12-03 10:20  Modified: 2010-12-05 19:30 ...
```

Or it's separated into multiple lines with double line breaks if I insert each line in one paragraph. However Pelican requires having lines in sequence and doesn't recognize empty lines. 

https://docs.getpelican.com/en/3.6.3/content.html#file-metadata

I was looking into the code to find if I can modify some class to allow line break but I only found this line which adds double lines between elements `\n\n`:
https://github.com/TheRenegadeCoder/SnakeMD/blob/main/snakemd/generator.py#L1130

I've tried to have `<br>`, `<br/>` and `\n` in  my string but that didn't help.

Could you please allow having single new line as in the example above.

**Comment by jrg94** [comment]
Good call! I’ll have to dig into this a bit more. I think a short term solution would be to create a simple class similar to horizontal rule that lets you add the extra new lines yourself. Previously, I had looked into including a wrap feature (if this is related #51) to the document class, so I have some ideas how this could be accomplished in other ways. Regardless, I probably won’t be able to get to this soon as I’m caring for a parent. If you have some ideas, feel free to make a pull request, and I’ll take a look.

**Comment by jrg94** [comment]
In the short term, you might try converting your markdown document to a string and building the file yourself with your preferred format. I believe I did something like this here: https://github.com/TheRenegadeCoder/sample-programs-website/blob/main/scripts/automate.py.

**Comment by jrg94** [comment]
I'm adding a Raw block now, so you can insert preformatted text into your markdown documents.
