### ISSUE TITLE
NameError on table alignment 

### ISSUE THREAD

**Issue by barnumbirr** [TheRenegadeCoder/SnakeMD#69]
Hey,

thanks for creating the library, makes it actually fun and easy to create Markdown in Python.
Seems the `align` parameter on `add_table` is broken as the example docs both fail:

```python

# Taken from https://www.snakemd.io/en/latest/snake/#snakemd.generator.Document.add_table

import snakemd
doc = snakemd.new_doc("example")

doc.add_table(
    ["Place", "Name"],
    [
        ["1st", "Robert"],
        ["2nd", "Rae"]
    ],
    [Table.Align.CENTER, Table.Align.RIGHT],
    0
)
doc.output_page()

Traceback (most recent call last):
  File "main.py", line 26, in <module>
    [Table.Align.CENTER, Table.Align.RIGHT],
NameError: name 'Table' is not defined
```

and

```python

# Taken from https://github.com/TheRenegadeCoder/SnakeMD#tables

import snakemd
doc = snakemd.new_doc("example")

doc.add_table(
    ["Height (cm)", "Weight (kg)", "Age (y)"],
    [
        ['150', '70', '21'],
        ['164', '75', '19'],
        ['181', '87', '40']
    ],
    [Table.Align.LEFT, Table.Align.CENTER, Table.Align.RIGHT],
    0
)
doc.output_page()
```

Cheers.

**Comment by barnumbirr** [comment]
I figured out that I could use `snakemd.Table.Align.LEFT` but wasn't sure if `[Table.Align.LEFT, Table.Align.CENTER, Table.Align.RIGHT]` was supposed to work or if the documentation was wrong. Thanks for clearing that up.
I'll whip up a PR for the docs over the weekend but I have an auxilary question the "new" `add_row` function that I think might be nice to the documentation as well.
How would I go about adding colum alignment to the following example:

```python
    table = snakemd.Table(['Username', 'Count'])
    for i in range(len(df)):
        table.add_row([df.iloc[i]['User'], df.iloc[i]['Frequency']])
    doc.add_element(table)
```

Cheers.

**Comment by jrg94** [comment]
I believe you'd have to add the align in the first line as follows:

```python
table = snakemd.Table(['Username', 'Count'], align=[snakemd.Table.Align.LEFT, snakemd.Table.Align.CENTER])
```
