### ISSUE TITLE
Ability to set custom _get_file_name separator

### ISSUE THREAD

**Issue by naxels** [TheRenegadeCoder/SnakeMD#70]
Thank you for creating the library, I'm using it to export several json files to Markdown
for use in Obsidian, which is very handy.

One thing that isn't so nice in Obsidian is the file name replacement with a - separator done by SnakeMD..
It will show up as the title of the document with all those -'s

example:
Documents display in Obsidian after doing doc.output_page():
> Research-done-by-doctor-X---no-1

which turns automatically into the Obsidian document title:
> Research-done-by-doctor-X---no-1

after which I myself have added a header:
> Research done by doctor X - no 1

Making it a total of 2 headers.

Could you make a change to the library to be able to change the separator if needed
with - being the default?

Thank you!

**Comment by jrg94** [comment]
Oh good call! I'm actually surprised it doesn't just take your file name supplied in the Document constructor. I must have thought I was being slick at some point to help with one of my other projects. Let me think about how I might rework this. In the short term, a solution where the separator could be provided would be better for sure. 

In the long term, I think I want to rework the document class, so it doesn't ask for a file name at all. I think it makes more sense for the output_page method to actually ask for the file name, so you could generate multiple files with the same contents with different names. Let me know if that makes sense.

**Comment by jrg94** [comment]
Yeah, I think my long term plan makes more sense. These two lines in the constructor are literally used in only one place:

```python
        self._name: str = name
        self._ext: str = ".md"
```

This method probably doesn't need to exist:

```python
def _get_file_name(self) -> str:
        """
        A helper function for generating the file name.
        """
        separator = "-"
        file_name = f"{separator.join(self._name.split())}{self._ext}"
        return file_name
```
